import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    padding: 16,
    backgroundColor: "#fff",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
  },
  backHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
  },
  backLabel: {
    fontSize: 16,
    marginLeft: 8,
    color: "#000",
    fontWeight: "bold",
  },
  imageWrapper: {
    position: "relative",
    width: "100%",
  },
  eventImage: {
    width: "100%",
    height: 250,
    resizeMode: "cover",
  },
  overlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    padding: 16,
  },
  backOverlayButton: {
    position: "absolute",
    top: 16,
    left: 16,
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    borderRadius: 20,
    padding: 8,
    zIndex: 1,
  },
  eventName: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 4,
    textAlign: "center",
  },
  location: {
    fontSize: 16,
    color: "#eee",
    marginBottom: 2,
  },
  date: {
    fontSize: 14,
    color: "#ccc",
  },
  description: {
    marginTop: 10,
    fontSize: 24,
    textAlign: "center",
  },
  sectionTitle: {
    marginTop: 20,
    fontSize: 18,
    fontWeight: "bold",
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    paddingBottom: 5,
  },
  ticketCard: {
    backgroundColor: "#fff3e6",
    padding: 16,
    borderRadius: 10,
    marginBottom: 12,
  },
  ticketType: {
    fontWeight: "bold",
    fontSize: 16,
    marginBottom: 4,
  },
  price: {
    color: "#e67e22",
    fontWeight: "bold",
    marginTop: 4,
  },
  quantityContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 10,
    justifyContent: "space-between",
  },
  selectText: {
    fontSize: 16,
    color: "#333",
    fontWeight: "600",
  },
  selectedInfo: {
    fontSize: 14,
    color: "#28a745", // Màu xanh để nổi bật
    marginTop: 8,
  },
  picker: {
    width: 100,
    height: 60,
    backgroundColor: "#fff3e6",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ddd",
    paddingHorizontal: 10,
    color: "#333",
    justifyContent: "center",
  },
  activityCard: {
    backgroundColor: "#e6f7ff",
    padding: 16,
    borderRadius: 10,
    marginBottom: 12,
  },
  activityName: {
    fontWeight: "bold",
    fontSize: 16,
  },
  activityDetail: {
    marginTop: 6,
  },
  activityDesc: {
    color: "#333",
  },
  activityNote: {
    color: "#666",
    fontStyle: "italic",
    marginTop: 2,
  },
  totalContainer: {
    marginTop: 20,
    padding: 16,
    backgroundColor: "#fff0f5",
    borderRadius: 10,
    alignItems: "center",
  },
  totalText: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 10,
    color: "#e6005c",
  },
  orderButton: {
    backgroundColor: "#ff3399",
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderRadius: 8,
  },
  orderText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  characterGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  characterCardWrapper: {
    width: "48%",
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 10,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  oddLastCharacter: {
    alignSelf: "center",
  },
  singleCharacterCard: {
    width: "100%",
  },
  characterImage: {
    width: "100%",
    height: 150,
    borderRadius: 10,
    marginBottom: 8,
    resizeMode: "contain",
  },
  characterName: {
    fontWeight: "bold",
    fontSize: 16,
    marginBottom: 6,
    textAlign: "center",
  },
  characterDetail: {
    marginTop: 6,
  },
});